/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IFactory, IFactoryInterface } from "../../interfaces/IFactory.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "allPairs",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "allPairsLength",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IFactory__factory {
    static readonly abi = _abi;
    static createInterface(): IFactoryInterface {
      return new Interface(_abi) as IFactoryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IFactory {
      return new Contract(address, _abi, runner) as unknown as IFactory;
    }
  }
  