/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPair, IPairInterface } from "../../interfaces/IPair.js";

  const _abi = [
  {
    "inputs": [],
    "name": "getReserves",
    "outputs": [
      {
        "internalType": "uint112",
        "name": "",
        "type": "uint112"
      },
      {
        "internalType": "uint112",
        "name": "",
        "type": "uint112"
      },
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "token0",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "token1",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IPair__factory {
    static readonly abi = _abi;
    static createInterface(): IPairInterface {
      return new Interface(_abi) as IPairInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPair {
      return new Contract(address, _abi, runner) as unknown as IPair;
    }
  }
  