/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'SwapExecutor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SwapExecutor__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'IPair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPair__factory>
getContractFactory(name: 'IFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFactory__factory>
getContractFactory(name: 'IUniswapV2Router02', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Router02__factory>
getContractFactory(name: 'MockBadToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockBadToken__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'MockRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockRouter__factory>

  getContractAt(name: 'SwapExecutor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SwapExecutor>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'IPair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPair>
getContractAt(name: 'IFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFactory>
getContractAt(name: 'IUniswapV2Router02', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Router02>
getContractAt(name: 'MockBadToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockBadToken>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'MockRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockRouter>

  deployContract(name: 'SwapExecutor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SwapExecutor>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'IPair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPair>
deployContract(name: 'IFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFactory>
deployContract(name: 'IUniswapV2Router02', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Router02>
deployContract(name: 'MockBadToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockBadToken>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'MockRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockRouter>

  deployContract(name: 'SwapExecutor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SwapExecutor>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'IPair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPair>
deployContract(name: 'IFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFactory>
deployContract(name: 'IUniswapV2Router02', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Router02>
deployContract(name: 'MockBadToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockBadToken>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'MockRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockRouter>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  