/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockRouterSol from './MockRouter.sol/index.js';
export type { mockRouterSol };
export type { MockBadToken } from './MockBadToken.js';
export type { MockERC20 } from './MockERC20.js';