/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { MockRouter, MockRouterInterface } from "../../../mocks/MockRouter.sol/MockRouter.js";

  const _abi = [
  {
    "inputs": [],
    "name": "rate",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "newRate",
        "type": "uint256"
      }
    ],
    "name": "setRate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "path",
        "type": "address[]"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "swapExactTokensForTokens",
    "outputs": [
      {
        "internalType": "uint256[]",
        "name": "amounts",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080806040523460195760645f55610324908161001e8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081632c4e722e146102735750806334fcf4371461025b576338ed17391461003d575f80fd5b346102575760a03660031901126102575760443560043567ffffffffffffffff821161025757366023830112156102575781600401359167ffffffffffffffff8311610257573660248460051b83010111610257576064356001600160a01b03811691908290036102575783156101da575f60206001600160a01b036100c56024850161028c565b166064604051809481936323b872dd60e01b83523360048401523060248401528960448401525af1801561021b5761023a575b505f54808402908482041484151715610226576064900493600110156101da575f916020916044906001600160a01b039061013490830161028c565b1691604051948593849263a9059cbb60e01b845260048401528860248401525af1801561021b576101ee575b50604051916101706060846102a0565b60028352602083019160403684378351156101da5782528251600110156101da5760408392930152604051918291602083019060208452518091526040830191905f5b8181106101c1575050500390f35b82518452859450602093840193909201916001016101b3565b634e487b7160e01b5f52603260045260245ffd5b61020f9060203d602011610214575b61020781836102a0565b8101906102d6565b610160565b503d6101fd565b6040513d5f823e3d90fd5b634e487b7160e01b5f52601160045260245ffd5b6102529060203d6020116102145761020781836102a0565b6100f8565b5f80fd5b34610257576020366003190112610257576004355f55005b34610257575f366003190112610257576020905f548152f35b356001600160a01b03811681036102575790565b90601f8019910116810190811067ffffffffffffffff8211176102c257604052565b634e487b7160e01b5f52604160045260245ffd5b9081602091031261025757518015158103610257579056fea2646970667358221220d887aa71b2c9685e5a2dea16dd927ecda5af144880b28efa60613e8d64b81fb664736f6c634300081c0033";

  
      type MockRouterConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockRouterConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockRouter__factory extends ContractFactory {
    
      constructor(...args: MockRouterConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockRouter__factory {
      return super.connect(runner) as MockRouter__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockRouterInterface {
      return new Interface(_abi) as MockRouterInterface;
    }
    
    override attach(address: string | Addressable): MockRouter {
      return super.attach(address) as MockRouter;
    }
  static connect(address: string, runner?: ContractRunner | null): MockRouter {
      return new Contract(address, _abi, runner) as unknown as MockRouter;
    }
  }

  
  