/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from './IERC20.js';
export type { IFactory } from './IFactory.js';
export type { IPair } from './IPair.js';
export type { IUniswapV2Router02 } from './IUniswapV2Router02.js';