/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface SwapExecutorInterface extends Interface {
    getFunction(nameOrSignature: "addRouter" | "allowedRouters" | "executeSwap" | "owner" | "removeRouter"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RouterAdded" | "SwapExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'addRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'allowedRouters', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'executeSwap', values: [AddressLike[], AddressLike[], BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeRouter', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowedRouters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeSwap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeRouter', data: BytesLike): Result;
  }

  
    export namespace RouterAddedEvent {
      export type InputTuple = [router: AddressLike];
      export type OutputTuple = [router: string];
      export interface OutputObject {router: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapExecutedEvent {
      export type InputTuple = [user: AddressLike, path: AddressLike[], routers: AddressLike[], amountIn: BigNumberish, amountOut: BigNumberish];
      export type OutputTuple = [user: string, path: string[], routers: string[], amountIn: bigint, amountOut: bigint];
      export interface OutputObject {user: string, path: string[], routers: string[], amountIn: bigint, amountOut: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SwapExecutor extends BaseContract {
    
    connect(runner?: ContractRunner | null): SwapExecutor;
    waitForDeployment(): Promise<this>;

    interface: SwapExecutorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addRouter: TypedContractMethod<
      [router: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    allowedRouters: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    executeSwap: TypedContractMethod<
      [routers: AddressLike[], path: AddressLike[], amountIn: BigNumberish, amountOutMin: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeRouter: TypedContractMethod<
      [router: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addRouter'): TypedContractMethod<
      [router: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowedRouters'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'executeSwap'): TypedContractMethod<
      [routers: AddressLike[], path: AddressLike[], amountIn: BigNumberish, amountOutMin: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeRouter'): TypedContractMethod<
      [router: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'RouterAdded'): TypedContractEvent<RouterAddedEvent.InputTuple, RouterAddedEvent.OutputTuple, RouterAddedEvent.OutputObject>;
getEvent(key: 'SwapExecuted'): TypedContractEvent<SwapExecutedEvent.InputTuple, SwapExecutedEvent.OutputTuple, SwapExecutedEvent.OutputObject>;

    filters: {
      
      'RouterAdded(address)': TypedContractEvent<RouterAddedEvent.InputTuple, RouterAddedEvent.OutputTuple, RouterAddedEvent.OutputObject>;
      RouterAdded: TypedContractEvent<RouterAddedEvent.InputTuple, RouterAddedEvent.OutputTuple, RouterAddedEvent.OutputObject>;
    

      'SwapExecuted(address,address[],address[],uint256,uint256)': TypedContractEvent<SwapExecutedEvent.InputTuple, SwapExecutedEvent.OutputTuple, SwapExecutedEvent.OutputObject>;
      SwapExecuted: TypedContractEvent<SwapExecutedEvent.InputTuple, SwapExecutedEvent.OutputTuple, SwapExecutedEvent.OutputObject>;
    
    };
  }