/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockBadToken, MockBadTokenInterface } from "../../mocks/MockBadToken.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "approve",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "transfer",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "transferFrom",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080806040523460135760da908160188239f35b5f80fdfe608060405260043610156010575f80fd5b5f3560e01c8063095ea7b314603657806323b872dd14603a5763a9059cbb146036575f80fd5b608f565b346061576060366003190112606157604f6065565b506056607a565b5060206040515f8152f35b5f80fd5b600435906001600160a01b0382168203606157565b602435906001600160a01b0382168203606157565b3460615760403660031901126061576056606556fea2646970667358221220319ef3f9ce8c94cb51bb7b37fb4ddeca060d865b656589666b546e5336d4234a64736f6c634300081c0033";

  
      type MockBadTokenConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockBadTokenConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockBadToken__factory extends ContractFactory {
    
      constructor(...args: MockBadTokenConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockBadToken & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockBadToken__factory {
      return super.connect(runner) as MockBadToken__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockBadTokenInterface {
      return new Interface(_abi) as MockBadTokenInterface;
    }
    
    override attach(address: string | Addressable): MockBadToken {
      return super.attach(address) as MockBadToken;
    }
  static connect(address: string, runner?: ContractRunner | null): MockBadToken {
      return new Contract(address, _abi, runner) as unknown as MockBadToken;
    }
  }

  
  